### ISSUE TITLE
[BUG] mcdev status bar, context menu and dependencies should only be activated in a mcdev project 

### ISSUE THREAD

**Issue by anasilva105** [Accenture/sfmc-devtools-vscode#104]
**Describe the bug**

mcdev in status bar, dependencies check and the context menu should only be activated if the project is a mcdev or there are in the same folder multiple mcdev projects. If not an error is showing up in the output console when the extension is not in a mcdev project.

**Comment by JoernBerkefeld** [comment]
is this really blocking for someone that wants to use mcdev? if it's just annoying but non-blocking, please move it to a bug release (1.0.x)
