### ISSUE TITLE
[BUG] Incorrect behaviour when trying to retrieve/deploy when single child folders are compressed 

### ISSUE THREAD

**Issue by anasilva105** [Accenture/sfmc-devtools-vscode#114]
**Describe the bug**
When a Business Unit folder has only a single metadata type folder when trying to retrieve another metadata type the extension is not able to detect the Business Unit folder click and will retrieve again the single metadata type that already exists. This is due to the fact that Visual Studio Code has enabled in Settings "Explorer: Compact Folders", making the path retrieve to the only configured folder.  

**To Reproduce**
1. Have a single Business Unit in the retrieve folder
2. Retrieve only **one** metadata type. If Compact Folder is enabled the folder will be shown as compacted
3. Try to retrieve another metadata type by right clicking on the same business unit
4. Command will run and retrieve the existing metadata type.

**Expected behavior**
The selection of metadata types popup should be shown everytime the use retrieves/deploys by selecting the Business Unit folder

**Screenshots**
![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/66126240/7bc9639b-436b-46c5-b247-c48246c3e553)

**Additional context**
Extension should setup in the settings explorer.compactFolders = false

**Comment by JoernBerkefeld** [comment]
"Extension should setup in the settings explorer.compactFolders = false"
no it shouldnt. That's a great feature and there might just be a workaround for it. 

related issues:
- #122 

kind of an edge issue: most users wont just retrieve one metadata type but go with default and retrieve all at once. I will therefore go ahead and move it back into milestone 1.0.1.

**Comment by JoernBerkefeld** [comment]
after a quick google search i would suggest opening a bug ticket here: https://github.com/microsoft/vscode/issues/new?assignees=&labels=&projects=&template=bug_report.md

also, maybe a more detailed search with your way of getting the folder path gets us to the finish line. my generic search didn't help
