### ISSUE TITLE
[FEATURE] add default right click menu to files in "open editors" menu

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-vscode#192]
![image](https://github.com/user-attachments/assets/7eb3f7a0-696e-468d-b9bd-8786fa39421f)

**Comment by anasilva105** [comment]
@JoernBerkefeld Cannot be implemented since currently vscode api weirdly does not support contributions/options to Open Editors menu.

An feature request has been open in the microsoft/vscode repository for this and can be found here https://github.com/microsoft/vscode/issues/209654

**Comment by JoernBerkefeld** [comment]
The feature request is closed due to insufficient up votes... :( guess we won't get that any time soon
