### ISSUE TITLE
[TASK] brainstorm on how long error state should be shown in bottom bar

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-vscode#221]
![image](https://github.com/user-attachments/assets/2d32d726-edbd-4e58-b227-de6033ae2585)

basically, this has the potential to confuse people

**Comment by anasilva105** [comment]
@JoernBerkefeld I added some logic related to this in the new PR. Basically after 10 sec both the icon and color go back to normal state.
