### ISSUE TITLE
[TASK] add mcdev as peer dependency

### ISSUE THREAD

**Issue by JoernBerkefeld** [Accenture/sfmc-devtools-vscode#33]
similar to what we've done in the copado repo (https://github.com/Accenture/sfmc-devtools-copado/blob/c0eb700def58c010d68787ad150fa3d4494b7305/package.json#LL12C10-L12C15) I would want you to add a definition of which mcdev version your extension requires in the form of a peer dependency in your package.json
```json
 "peerDependencies": {
        "mcdev": ">=5.1.0 < 6"
    },
```

read up on what nodejs has to say about Peer Dependencies: https://nodejs.org/en/blog/npm/peer-dependencies to understand what version definition could make sense and why this is interesting in the first place.

> The best way to determine what your peer dependency requirements should be is to actually follow [semver](http://semver.org/). Assume that only changes in the host package's major version will break your plugin. Thus, if you've worked with every 1.x version of the host package, use "~1.0" or "1.x" to express this. If you depend on features introduced in 1.5.2, use ">= 1.5.2 < 2".

... also, it will show up in the "used by" section afterwards ;-) 
![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/1917227/d021cdfb-86d6-478d-b6a0-ecbf2bf87cac)

**Comment by anasilva105** [comment]
Change it to 5.2.0 and above
