### ISSUE TITLE
[BUG] Retrieve/Deploy failing when key is a date 

### ISSUE THREAD

**Issue by anasilva105** [Accenture/sfmc-devtools-vscode#50]
Retrieve and Deploy are currently failing whenever a key is a date (for example).

To fix this bug it should split the filename by the "metadataype-meta"  instead

**Comment by JoernBerkefeld** [comment]
try this:

```js
fileName.split(/\.(\w|-)+-meta.json/)[0]
```

and this

```js
fileName.split(/\.(\w|-)+-doc.md/)[0]
```

it's what mcdev uses
