### ISSUE TITLE
[BUG] mcdev Upgrade not automatically updating after version is outdated

### ISSUE THREAD

**Issue by anasilva105** [Accenture/sfmc-devtools-vscode#68]
mcdev project needs to update version automatically in .mcdevrc.json

![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/66126240/e5d17bc8-a024-4edc-a151-85e5059c9627)

**Comment by JoernBerkefeld** [comment]
will be solved in mcdev 6.1.0. should not be handled in extension
